### ISSUE TITLE
Spend too much time to prepare data (ScanNet)

### ISSUE THREAD

**Issue by antao97** [hzykent/JSENet#2]
Thank you for your excellent work.

But I just want to cheak whether I run your code correctly, because it spends too much time to prepare data in ScanNet.
![log](https://user-images.githubusercontent.com/41320807/94656234-686aa600-0332-11eb-8094-473ee800b22f.png)

I also find your code have some mistakes, and they cause errors:

https://github.com/hzykent/JSENet/blob/362522d360cc17788b977232ed6aee9ce26273c3/JSENet_code/dataset_modules/Scannet.py#L294
I think `sub_points[i].reshape[1, -1]` should be replaced by `sub_points[i].reshape(1, -1)`, otherwise it reports error.

https://github.com/hzykent/JSENet/blob/362522d360cc17788b977232ed6aee9ce26273c3/JSENet_code/dataset_modules/Scannet.py#L298
I think `inds` should be replaced by `inds[0]`, otherwise it also reports error.

After I revised your code in the above two place, I find data preparation consumes too much time. For each scene it only needs less than 2 mins in KPConv.

My enviroment is tensorflow 1.12 and cuda 9.

**Comment by hzykent** [comment]
Thank you for your interest.

When I was working on this project, I wrote pretty messy codes for data preparation. This released version is a cleared up version for demonstrating the idea of the pipeline and not for efficiency. Since we need to check the neighborhood for each point in the dataset, the data preparation process is tedious and takes much time. I used multiprocessing to prepare the dataset and it still takes about one night to finish.

As for the two mistakes, I think you are right and I'll fix them.

**Comment by antao97** [comment]
Thanks for your quick response!

I roughly calculte the time for data preparation in this code, and find it needs more than 100 days...

I strongly recommend you to release your multiprocessing version, otherwise I can't use your code in my work.

**Comment by hzykent** [comment]
I'm afraid that I may not be able to provide the original code for data preparation since I'm away from HongKong and currently have no access to my office computer. But I guess the multiprocessing version is pretty straightforward. Copy the code in the dataset file and use the module multiprocessing will do the trick. Still takes one night though.

**Comment by antao97** [comment]
So I want to cheak whether I can reproduce your performance with this code, after I add multiprocessing in data preparation.

**Comment by hzykent** [comment]
I think so. The pretrained models and demo dataset for S3DIS are already provided. Let me know if you have further concerns.
